### ISSUE TITLE
edk2 for motorola one action (troika)

### ISSUE THREAD

**Issue by vizPilot** [calebccff/edk2-sdm845#1]
i have a motorola one action with exynos 9609 and i want to port edk2 for motorola one action for create edk2 for my motorola one action

**Comment by dsankouski** [comment]
@Vicc2008 ,  in order to port edk, stock bootloader should be UEFI, which may not be the case for exynos (at least it not for exynos7880)

**Comment by vizPilot** [comment]
ok
